#!/usr/bin/env python3
"""Validate a Sol closure receipt and re-execute its contract verification."""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

from lib_packets import (
    PacketError,
    WhyArgumentParser,
    decision_units_by_id,
    load_json_object,
    path_is_owned,
    print_why,
    reject_extra_keys,
    require,
    require_keys,
    require_string,
    run_verification,
    validate_declared_result,
    validate_verification_command,
)
from validate_sol_status import (
    build_skip_notice,
    compute_review_gate,
    git_changed_paths,
    validate_repo_diff,
    validate_status_packet,
)


def validate_skip_notice(value: dict[str, Any]) -> None:
    required = ("generated_by", "review_required", "status", "status_packet", "gate_rules", "skip_reasons")
    require_keys(value, required, where="skip notice")
    reject_extra_keys(value, required, where="skip notice")
    require(value["generated_by"] == "validate_sol_status.py", "skip notice was not generated by the deterministic validator")
    require(value["review_required"] is False, "skip notice cannot skip a required review")
    require(value["status"] == "READY", "skip notice requires READY status")
    require_string(value["status_packet"], where="skip_notice.status_packet")
    require(isinstance(value["gate_rules"], list) and len(value["gate_rules"]) == 4, "skip notice must record all four gate rules")
    rule_names: list[str] = []
    for index, rule in enumerate(value["gate_rules"]):
        where = f"skip_notice.gate_rules[{index}]"
        require(isinstance(rule, dict), f"{where} must be an object")
        require_keys(rule, ("rule", "triggered", "evidence"), where=where)
        reject_extra_keys(rule, ("rule", "triggered", "evidence"), where=where)
        rule_names.append(require_string(rule["rule"], where=f"{where}.rule"))
        require_string(rule["evidence"], where=f"{where}.evidence", min_length=8)
        require(rule["triggered"] is False, f"{where} is triggered, so review cannot be skipped")
    require(
        set(rule_names)
        == {
            "hold_present",
            "owned_path_or_material_deviation",
            "fable_owned_surface_touched",
            "verification_unclean",
        },
        "skip notice does not contain the exact four deterministic gate rules",
    )
    require(isinstance(value["skip_reasons"], list) and bool(value["skip_reasons"]), "skip notice must state why review was skipped")


def validate_receipt_packet(
    data: dict[str, Any],
    decision: dict[str, Any],
    status: dict[str, Any],
    *,
    status_packet_name: str,
    review: dict[str, Any] | None,
    skip_notice: dict[str, Any] | None,
) -> dict[str, Any]:
    fields = (
        "outcome",
        "findings_closed",
        "verification_reruns",
        "review_ran",
        "skip_reasons",
        "open_items",
        "boundary_attestation",
    )
    require_keys(data, fields, where="receipt")
    reject_extra_keys(data, fields, where="receipt")
    validate_status_packet(status, decision)
    computed_review_required, computed_reasons, computed_rules = compute_review_gate(status, decision)
    require(status.get("review_required") is computed_review_required, "staged status.review_required differs from deterministic recomputation")
    require(status.get("review_reasons") == computed_reasons, "staged status.review_reasons differ from deterministic recomputation")
    outcome = data["outcome"]
    require(outcome in {"DONE", "DONE_WITH_OPEN_ITEMS", "STOPPED"}, "outcome is not recognized")

    findings_closed = data["findings_closed"]
    require(isinstance(findings_closed, list), "findings_closed must be a list")
    closed_ids: list[str] = []
    for index, item in enumerate(findings_closed):
        where = f"findings_closed[{index}]"
        require(isinstance(item, dict), f"{where} must be an object")
        item_fields = ("id", "source", "evidence")
        require_keys(item, item_fields, where=where)
        reject_extra_keys(item, item_fields, where=where)
        closed_ids.append(require_string(item["id"], where=f"{where}.id"))
        require(item["source"] in {"review", "skip-notice"}, f"{where}.source is not review or skip-notice")
        require_string(item["evidence"], where=f"{where}.evidence", min_length=8)
    require(len(closed_ids) == len(set(closed_ids)), "findings_closed ids must be unique")

    decision_units = decision_units_by_id(decision)
    command_to_unit = {unit["verification_command"]: unit_id for unit_id, unit in decision_units.items()}
    reruns = data["verification_reruns"]
    require(isinstance(reruns, list), "verification_reruns must be a list")
    rerun_commands: list[str] = []
    for index, rerun in enumerate(reruns):
        where = f"verification_reruns[{index}]"
        require(isinstance(rerun, dict), f"{where} must be an object")
        require_keys(rerun, ("command", "result"), where=where)
        reject_extra_keys(rerun, ("command", "result"), where=where)
        command = validate_verification_command(rerun["command"], where=f"{where}.command")
        require(command in command_to_unit, f"{where}.command is not in the Fable decision contract")
        rerun_commands.append(command)
        validate_declared_result(rerun["result"], where=f"{where}.result")
    require(len(rerun_commands) == len(set(rerun_commands)), "verification_reruns commands must be unique")
    if outcome != "STOPPED":
        require(set(rerun_commands) == set(command_to_unit), "a non-stopped receipt must rerun every contract verification command")
        for index, rerun in enumerate(reruns):
            passed, exit_code = validate_declared_result(rerun["result"], where=f"verification_reruns[{index}].result")
            require(passed and exit_code == 0, "a non-stopped receipt requires every declared rerun to pass cleanly")

    require(isinstance(data["review_ran"], bool), "review_ran must be a boolean")
    require(data["review_ran"] is computed_review_required, "receipt review_ran does not match the recomputed deterministic gate")
    skip_reasons = data["skip_reasons"]
    require(isinstance(skip_reasons, list), "skip_reasons must be a list")
    for index, reason in enumerate(skip_reasons):
        require_string(reason, where=f"skip_reasons[{index}]", min_length=8)

    if data["review_ran"]:
        require(review is not None, "review_ran=true requires a staged review packet")
        require(skip_notice is None, "review_ran=true cannot consume a skip notice")
        require(not skip_reasons, "review_ran=true requires empty skip_reasons")
        require(review.get("verdict") in {"APPROVE", "REVISE", "ESCALATE"}, "staged review verdict is not recognized")
        review_findings = review.get("findings")
        require(isinstance(review_findings, list), "staged review findings must be a list")
        review_ids: set[str] = set()
        for index, item in enumerate(review_findings):
            require(isinstance(item, dict), f"staged review findings[{index}] must be an object")
            review_ids.add(require_string(item.get("id"), where=f"staged review findings[{index}].id"))
        require(len(review_ids) == len(review_findings), "staged review finding ids must be unique")
        require(all(item["source"] == "review" for item in findings_closed), "review closure entries must map to review")
        require(set(closed_ids).issubset(review_ids), "a closed finding id is absent from staged review")
        if outcome == "DONE":
            require(set(closed_ids) == review_ids, "DONE must close every staged review finding")
        require(review.get("verdict") != "ESCALATE" or outcome == "STOPPED", "an ESCALATE review cannot produce a completed receipt")
    else:
        require(review is None, "review_ran=false cannot consume a review packet")
        require(skip_notice is not None, "review_ran=false requires the generated skip notice")
        validate_skip_notice(skip_notice)
        expected_notice = build_skip_notice(Path(status_packet_name), computed_rules, computed_reasons)
        require(skip_notice == expected_notice, "skip notice does not match deterministic recomputation from staged status")
        require(skip_reasons == skip_notice["skip_reasons"], "receipt skip_reasons must exactly match the generated skip notice")
        require(len(findings_closed) == 1, "a skipped review receipt must map one closure record to the skip notice")
        require(findings_closed[0]["source"] == "skip-notice" and findings_closed[0]["id"] == "SKIP_NOTICE", "skipped review closure must use id SKIP_NOTICE and source skip-notice")

    open_items = data["open_items"]
    require(isinstance(open_items, list), "open_items must be a list")
    for index, item in enumerate(open_items):
        require_string(item, where=f"open_items[{index}]", min_length=8)
    if outcome == "DONE":
        require(not open_items, "DONE cannot contain open_items")
    else:
        require(bool(open_items), f"{outcome} requires at least one open item")

    attestation = data["boundary_attestation"]
    require(isinstance(attestation, dict), "boundary_attestation must be an object")
    attestation_fields = ("forbidden_actions_taken", "external_actions_taken", "sol_accepted_own_work", "statement")
    require_keys(attestation, attestation_fields, where="boundary_attestation")
    reject_extra_keys(attestation, attestation_fields, where="boundary_attestation")
    require(attestation["forbidden_actions_taken"] == [], "boundary_attestation reports a forbidden action")
    require(attestation["external_actions_taken"] == [], "boundary_attestation reports an external action")
    require(attestation["sol_accepted_own_work"] is False, "Sol cannot accept its own work")
    require_string(attestation["statement"], where="boundary_attestation.statement", min_length=20)
    return data


def execute_receipt_verification(data: dict[str, Any], *, repo: Path, timeout_s: int) -> None:
    for index, rerun in enumerate(data["verification_reruns"]):
        proc = run_verification(rerun["command"], cwd=repo, timeout_s=timeout_s)
        declared_passed, _declared_exit = validate_declared_result(rerun["result"], where=f"verification_reruns[{index}].result")
        actual_passed = proc.returncode == 0
        if actual_passed != declared_passed:
            detail = (proc.stderr.strip() or proc.stdout.strip() or "no process output")[-1200:]
            raise PacketError(f"verification rerun result was quoted rather than executed accurately for command {rerun['command']!r}: exit={proc.returncode}; {detail}")


def enforce_owned_git_diff(decision: dict[str, Any], repo: Path) -> None:
    outside = [path for path in git_changed_paths(repo) if not path_is_owned(path, decision["owned_paths"])]
    require(not outside, f"git porcelain contains changes outside owned_paths: {', '.join(outside)}")


def main(argv: list[str] | None = None) -> int:
    parser = WhyArgumentParser(description=__doc__)
    parser.add_argument("--packet", type=Path, required=True)
    parser.add_argument("--decision", type=Path, required=True)
    parser.add_argument("--status", type=Path, required=True)
    parser.add_argument("--repo", type=Path, required=True)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--review", type=Path)
    source.add_argument("--skip-notice", type=Path)
    parser.add_argument("--timeout", type=int, default=300)
    args = parser.parse_args(argv)
    try:
        require(1 <= args.timeout <= 1800, "--timeout must be between 1 and 1800 seconds")
        data = load_json_object(args.packet)
        decision = load_json_object(args.decision)
        status = load_json_object(args.status)
        review = load_json_object(args.review) if args.review else None
        skip_notice = load_json_object(args.skip_notice) if args.skip_notice else None
        validate_receipt_packet(
            data,
            decision,
            status,
            status_packet_name=args.status.name,
            review=review,
            skip_notice=skip_notice,
        )
        enforce_owned_git_diff(decision, args.repo.resolve())
        if skip_notice is not None:
            validate_repo_diff(status, decision, args.repo.resolve())
        execute_receipt_verification(data, repo=args.repo.resolve(), timeout_s=args.timeout)
    except (PacketError, OSError) as exc:
        print_why(exc)
        return 1
    print(f"PASS: valid Sol receipt ({data['outcome']}); verification was re-executed and authority stayed bounded")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # pragma: no cover
        print_why(exc)
        sys.exit(1)
